### PR TITLE
Upload deamon fixes

### LINKED ISSUE #103: Move trace files that produce no coverage?
Currently, the profiler leaves tracefiles that produce no coverage in place and retries them every time. However, if we trace some processes that may not always run through relevant assembly code, we accumulate an ever-growing number of no-coverage files that are retried every 5 minutes. We should move these files into a `no-coverage` folder instead.

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #103, #106, #92 

- [x] Tests written
- [ ] Documentation updated -> not needed

### CODE REVIEW

**Comment by karottenreibe** [comment]
rfr @salsolatragus

File: UploadDaemon/service/README [hunk 1]
```diff
@@ -0,0 +1,40 @@
+The contents of this directory can be used to install Teamscale as a windows
```
Comment (salsolatragus) [inline UploadDaemon/service/README]: This talks about Teamscale, should be UploadDaemon.

File: UploadDaemon/UploadDaemon.cs [hunk 2]
```diff
@@ -81,27 +67,55 @@ private static bool IsAlreadyRunning()
...
+            Config config;
+            try
+            {
+                logger.Debug("Reading config from {configFile}", Config.ConfigFilePath);
+                config = Config.ReadFromCentralConfigFile();
+            }
+            catch (Exception e)
+            {
+                logger.Error(e, "Failed to read config file {configPath}", Config.ConfigFilePath);
+                return null;
```
Comment (salsolatragus) [inline UploadDaemon/UploadDaemon.cs]: I would move the exception handling to the callsite, to avoid passing around null. A method named ReadConfig may throw if reading fails imho.

File: UploadDaemon/UploadDaemon.cs [hunk 3]
```diff
@@ -81,27 +67,55 @@ private static bool IsAlreadyRunning()
...
 
         /// <summary>
         /// Uploads once, synchronously.
         /// </summary>
         public void UploadOnce()
+        {
+            Config config = ReadConfig();
+            if (config == null)
+            {
+                return;
```
Comment (salsolatragus) [inline UploadDaemon/UploadDaemon.cs]: Handling the exception here would allow “auto-skipping” the upload.

File: UploadDaemon/UploadTask.cs [hunk 4]
```diff
@@ -156,4 +161,4 @@ private static async Task ProcessMethodCoverage(TraceFile trace, Archiver archiv
             }
         }
     }
-}
+}
```
Comment (salsolatragus) [inline UploadDaemon/UploadTask.cs]: Missing newline

File: UploadDaemon/service/UploadDaemonService.xml [hunk 5]
```diff
@@ -0,0 +1,33 @@
+<service>
+	<id>teamscale-dotnet-profiler-upload-daemon</id>
+	<name>Teamscale DotNet Profiler UploadDaemon</name>
+	<description>Teamscale DotNet Profiler UploadDaemon</description>
+
+	<!-- Adjust these paths to your setup. -->
+	<!-- PROFILER_DIR should be the path that contains Profiler32.dll -->
+	<env name="PROFILER_DIR" value="c:\path\to\profiler" />
+
+	<executable>%PROFILER_DIR%\UploadDaemon\UploadDaemon.exe
```
Comment (salsolatragus) [inline UploadDaemon/service/UploadDaemonService.xml]: Is this trailing newline ok?

File: UploadDaemon/service/UploadDaemonService.xml [hunk 6]
```diff
@@ -0,0 +1,33 @@
+<service>
+	<id>teamscale-dotnet-profiler-upload-daemon</id>
+	<name>Teamscale DotNet Profiler UploadDaemon</name>
+	<description>Teamscale DotNet Profiler UploadDaemon</description>
+
+	<!-- Adjust these paths to your setup. -->
+	<!-- PROFILER_DIR should be the path that contains Profiler32.dll -->
```
Comment (salsolatragus) [inline UploadDaemon/service/UploadDaemonService.xml]: Or Profiler64.dll?

File: UploadDaemon_Test/UploadTaskTest.cs [hunk 7]
```diff
@@ -247,9 +264,24 @@ public Task<bool> UploadLineCoverageAsync(string originalTraceFilePath, string l
 
     private class MockLineCoverageSynthesizer : ILineCoverageSynthesizer
     {
+        private readonly bool shouldProduceCoverage;
+
+        public MockLineCoverageSynthesizer() : this(true)
```
Comment (salsolatragus) [inline UploadDaemon_Test/UploadTaskTest.cs]: You could use an optional parameter for this (`bool shouldProduceCoverage = true`).

File: UploadDaemon/UploadTask.cs (hunk 4 above)
Comment (karottenreibe) [reply UploadDaemon/UploadTask.cs]: I changed the formatter settings to insert newlines

File: UploadDaemon/service/UploadDaemonService.xml (hunk 5 above)
Comment (karottenreibe) [reply UploadDaemon/service/UploadDaemonService.xml]: Yes, was like that for Teamscale as well

File: UploadDaemon/service/UploadDaemonService.xml (hunk 6 above)
Comment (karottenreibe) [reply UploadDaemon/service/UploadDaemonService.xml]: Yes, but they'll both be present always, so I didn't bother to include that ;-)

**Comment by karottenreibe** [comment]
rfr agaun

File: README.md [hunk 8]
```diff
@@ -15,6 +15,8 @@ Documentation on installation and usage of the profiler can be found [here](./do
 ## Contributing
 
 The coverage profiler can be compiled using Visual Studio 2017. Ensure to have the Windows and .NET SDK installed.
+Please also install [CodeMaid][] to enable formatting the source code automatically on save. This keeps the
```
Comment (salsolatragus) [inline README.md]: missing link id
