### PR TITLE
remove profiler GUI

### LINKED ISSUE #136: Remove Profiler GUI
It doesn't work anymore (not since quite a while) and making it work again is a major effort. On the other hand, we haven't needed it in quite a while, so I'd rather remove it from the source and dist and get it back from the Git history if we should need it.

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #136 #88 #87 #86 #85 #73 #72 #71 #70 #69 #68 #31 #26 

- [ ] Tests written - not needed
- [x] Documentation updated

Please respect the [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-net-profiler) vote. Clean up findings before sending your change into review. Blacklist and report false-positives. Adjust the analysis profile if needed.

### CODE REVIEW

**Comment by karottenreibe** [comment]
@AnonymFx: @mpdeimos doesn't seem to have time to review this, would you mind reviewing it? It's mostly just deleted code ;-)

**Comment by AnonymFx** [comment]
:ok_hand:

**Comment by karottenreibe** [comment]
Thanks, good points! And sorry for the very late rework, I was too busy with urgent stuff the last few weeks :-(

I'd leave the test data as is since it's too much work changing it. If we ever need new tests or change these existing tests, we can create new test data. I think that should be fine :-)

Thanks to your review I also realized that we no longer need the Common project, so I merged its code back into the UploadDaemon.

Then I realized that we have no architecture definition, so I created one and in the process, moved some code around that wasn't in the right place.

**Comment by AnonymFx** [comment]
No problem :)

It'll take some time until I get to the next review as well, as it's the time of the month where there's a lot to do in my other team. ;) I'll try to fit it in next week or the week after that, though.

File: UploadDaemon/Configuration/Config.cs [hunk 1]
```diff
@@ -3,17 +3,17 @@
...
 using System.Text.RegularExpressions;
 using System.Linq;
-using static Common.ConfigParser;
+using UploadDaemon.Utils;
 
-namespace Common
+namespace UploadDaemon.Configuration
 {
     /// <summary>
     /// Stores the uploader's config and applies it depending on the
```
Comment (AnonymFx) [inline UploadDaemon/Configuration/Config.cs]: There's something missing at the end of the comment ^^ We might as well fix it with this pull request ;)

File: UploadDaemon/Configuration/ConfigParser.cs [hunk 2]
```diff
@@ -186,4 +186,4 @@ public static YamlConfig Parse(string yaml)
             return result;
         }
     }
-}
+}
```
Comment (AnonymFx) [inline UploadDaemon/Configuration/ConfigParser.cs]: I assume all of these are Linux/Windows line ending changes. What do we actually use in this project? Can we somewhere define it in the project settings which are transferred via git?

File: UploadDaemon/SymbolAnalysis/LineCoverageSynthesizer.cs [hunk 3]
```diff
@@ -1,11 +1,12 @@
-﻿using Common;
+﻿using UploadDaemon;
```
Comment (AnonymFx) [inline UploadDaemon/SymbolAnalysis/LineCoverageSynthesizer.cs]: Can be removed

File: UploadDaemon/SymbolAnalysis/LineCoverageSynthesizer.cs [hunk 4]
```diff
@@ -1,11 +1,12 @@
...
 using Cqse.ConQAT.Dotnet.Bummer;
 using NLog;
 using System;
 using System.Collections.Generic;
 using System.IO.Abstractions;
```
Comment (AnonymFx) [inline UploadDaemon/SymbolAnalysis/LineCoverageSynthesizer.cs]: Can be removed

File: UploadDaemon/Upload/IUploadFactory.cs [hunk 5]
```diff
@@ -1,5 +1,6 @@
-﻿using Common;
+﻿using UploadDaemon;
```
Comment (AnonymFx) [inline UploadDaemon/Upload/IUploadFactory.cs]: Can be removed

File: UploadDaemon/UploadDaemon.cs [hunk 6]
```diff
@@ -1,4 +1,4 @@
-using Common;
+using UploadDaemon;
```
Comment (AnonymFx) [inline UploadDaemon/UploadDaemon.cs]: Can be removed

File: UploadDaemon/Utils/GlobPatternList.cs [hunk 7]
```diff
@@ -5,7 +5,7 @@
 using System.Text.RegularExpressions;
 using System.Threading.Tasks;
```
Comment (AnonymFx) [inline UploadDaemon/Utils/GlobPatternList.cs]: Can be removed

File: UploadDaemon_Test/Archiving/PurgeArchiveTaskTest.cs [hunk 8]
```diff
@@ -1,7 +1,8 @@
-﻿using Common;
+﻿using UploadDaemon;
```
Comment (AnonymFx) [inline UploadDaemon_Test/Archiving/PurgeArchiveTaskTest.cs]: Can be removed

File: UploadDaemon_Test/Config/ConfigParserTest.cs [hunk 9]
```diff
@@ -1,7 +1,8 @@
 ﻿using NUnit.Framework;
 using System;
+using UploadDaemon.Configuration;
 
-namespace Common
+namespace UploadDaemon
```
Comment (AnonymFx) [inline UploadDaemon_Test/Config/ConfigParserTest.cs]: Should probably be in `UplaodDaemon.Configuration`

File: UploadDaemon_Test/Config/ConfigParserTest.cs [hunk 10]
```diff
@@ -1,7 +1,8 @@
 ﻿using NUnit.Framework;
 using System;
+using UploadDaemon.Configuration;
```
Comment (AnonymFx) [inline UploadDaemon_Test/Config/ConfigParserTest.cs]: Can be removed after moving to `UplaodDaemon.Configuration`

File: UploadDaemon_Test/Config/ConfigTest.cs [hunk 11]
```diff
@@ -1,8 +1,9 @@
 ﻿using NUnit.Framework;
 using System;
 using System.Collections.Generic;
+using UploadDaemon.Configuration;
 
-namespace Common
+namespace UploadDaemon
```
Comment (AnonymFx) [inline UploadDaemon_Test/Config/ConfigTest.cs]: Should also be in `UploadDaemon.Configuration`

File: UploadDaemon_Test/Config/ConfigTest.cs [hunk 12]
```diff
@@ -1,8 +1,9 @@
 ﻿using NUnit.Framework;
 using System;
 using System.Collections.Generic;
+using UploadDaemon.Configuration;
```
Comment (AnonymFx) [inline UploadDaemon_Test/Config/ConfigTest.cs]: Can be removed after moving to `UploadDaemon.Configuration`

File: UploadDaemon_Test/SymbolAnalysis/GlobPatternListTest.cs [hunk 13]
```diff
@@ -1,6 +1,6 @@
 ﻿using NUnit.Framework;
-using Common;
 using System.Collections.Generic;
+using UploadDaemon.Utils;
 
 [TestFixture]
 public class GlobPatternListTest
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/GlobPatternListTest.cs]: Move to namespace `UploadDaemon.Utils` or `UploadDaemon.SymbolAnalysis` depending on the decision where  `GlobPatternList.cs` should be located.

File: UploadDaemon_Test/SymbolAnalysis/LineCoverageSynthesizerTest.cs [hunk 14]
```diff
@@ -1,13 +1,9 @@
...
-using System.IO;
 using System.Collections.Generic;
-
-using System.IO.Abstractions;
-using Moq;
 using Cqse.ConQAT.Dotnet.Bummer;
+using UploadDaemon.Utils;
 
 [TestFixture]
 public class LineCoverageSynthesizerTest
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/LineCoverageSynthesizerTest.cs]: Move to namespace `UploadDaemon.SymbolAnalysis`?

File: UploadDaemon_Test/SymbolAnalysis/LineCoverageSynthesizerTest.cs [hunk 15]
```diff
@@ -53,7 +49,7 @@ public void ExcludingAllPdbsShouldResultInException()
 
         Exception exception = Assert.Throws<LineCoverageSynthesizer.LineCoverageConversionFailedException>(() =>
         {
-            Convert(traceFile, TestUtils.TestDataDirectory, new Common.GlobPatternList(new List<string> { "xx" }, new List<string> { "*" }));
+            LineCoverageSynthesizerTest.Convert(traceFile, TestUtils.TestDataDirectory, new GlobPatternList(new List<string> { "xx" }, new List<string> { "*" }));
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/LineCoverageSynthesizerTest.cs]: `LineCoverageSynthesizerTest.` can be removed

File: UploadDaemon_Test/SymbolAnalysis/ParsedTraceFileTest.cs [hunk 16]
```diff
@@ -1,5 +1,5 @@
 ﻿using NUnit.Framework;
-using Common;
+using UploadDaemon;
 using System.Collections.Generic;
 using UploadDaemon.SymbolAnalysis;
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/ParsedTraceFileTest.cs]: Move to `UploadDaemon.SymbolAnalysis`? If so, this line can be removed

File: UploadDaemon_Test/SymbolAnalysis/SymbolCollectionTest.cs [hunk 17]
```diff
@@ -5,6 +5,7 @@
 using System.IO;
 using System.Collections.Generic;
 using System.IO.Abstractions;
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/SymbolCollectionTest.cs]: Can be removed along with some other using statements.

File: UploadDaemon_Test/SymbolAnalysis/SymbolCollectionTest.cs [hunk 18]
```diff
@@ -5,6 +5,7 @@
...
+using UploadDaemon.Utils;
 
 [TestFixture]
 public class SymbolCollectionTest
```
Comment (AnonymFx) [inline UploadDaemon_Test/SymbolAnalysis/SymbolCollectionTest.cs]: Move to `UploadDaemon.SymbolAnalysis`? Remove corresponding using statement if you decide to do so.

File: UploadDaemon_Test/TraceFileScannerTest.cs [hunk 19]
```diff
@@ -5,7 +5,7 @@
 using System.IO.Abstractions;
 using System.IO.Abstractions.TestingHelpers;
 using System.Linq;
-using UploadDaemon;
+using UploadDaemon.Scanning;
 
 [TestFixture]
 public class TraceFileScannerTest
```
Comment (AnonymFx) [inline UploadDaemon_Test/TraceFileScannerTest.cs]: Move to `UplaodDaemon.Scanning`? If you do, remove corresponding using statement.

File: UploadDaemon_Test/UploadDaemonSystemTest.cs [hunk 20]
```diff
@@ -1,10 +1,11 @@
-﻿using Common;
+﻿using UploadDaemon;
 using NUnit.Framework;
 using System;
 using System.Collections.Generic;
 using System.IO;
 using System.Linq;
 using System.Threading;
```
Comment (AnonymFx) [inline UploadDaemon_Test/UploadDaemonSystemTest.cs]: Can be removed.

File: UploadDaemon_Test/UploadDaemonSystemTest.cs [hunk 21]
```diff
@@ -1,10 +1,11 @@
-﻿using Common;
+﻿using UploadDaemon;
 using NUnit.Framework;
 using System;
```
Comment (AnonymFx) [inline UploadDaemon_Test/UploadDaemonSystemTest.cs]: Can be removed.

File: UploadDaemon_Test/UploadDaemonSystemTest.cs [hunk 22]
```diff
@@ -1,10 +1,11 @@
-﻿using Common;
+﻿using UploadDaemon;
```
Comment (AnonymFx) [inline UploadDaemon_Test/UploadDaemonSystemTest.cs]: Can be removed.

File: UploadDaemon_Test/UploadTaskTest.cs [hunk 23]
```diff
@@ -7,9 +7,10 @@
 using System.IO.Abstractions.TestingHelpers;
 using System.Linq;
 using System.Threading.Tasks;
-using UploadDaemon;
 using UploadDaemon.SymbolAnalysis;
 using UploadDaemon.Upload;
```
Comment (AnonymFx) [inline UploadDaemon_Test/UploadTaskTest.cs]: Move to `UplaodDaemon.Upload` and remove this line?

File: UploadDaemon/UploadDaemon.csproj [hunk 24]
```diff
@@ -106,8 +106,8 @@
     <Compile Include="Archiving\IDateTimeProvider.cs" />
     <Compile Include="Configuration\Config.cs" />
     <Compile Include="Configuration\ConfigParser.cs" />
-    <Compile Include="LineCoverageMerger.cs" />
-    <Compile Include="MessageFormatter.cs" />
+    <Compile Include="Upload\LineCoverageMerger.cs" />
+    <Compile Include="Utils\MessageFormatter.cs" />
```
[the remark this answers is not in the document]
Comment (karottenreibe) [reply UploadDaemon/UploadDaemon.csproj]: I moved the GlobPatternList to Configuration since it's used there as well and I didn't want a dependency from Config to SymbolAnalysis, but otherwise implemented your changes as suggested

File: UploadDaemon/UploadDaemon.csproj [hunk 25]
```diff
@@ -116,10 +116,10 @@
     <Compile Include="SymbolAnalysis\ParsedTraceFile.cs" />
     <Compile Include="SymbolAnalysis\SymbolCollection.cs" />
     <Compile Include="UploadTask.cs" />
-    <Compile Include="TraceFile.cs" />
-    <Compile Include="TraceFileScanner.cs" />
+    <Compile Include="Scanning\TraceFile.cs" />
+    <Compile Include="Scanning\TraceFileScanner.cs" />
     <Compile Include="Properties\AssemblyInfo.cs" />
-    <Compile Include="Upload\AzureFileStorage.cs" />
+    <Compile Include="Configuration\AzureFileStorage.cs" />
```
[the remark this answers is not in the document]
Comment (karottenreibe) [reply UploadDaemon/UploadDaemon.csproj]: These are both used in Configuration/Config.cs, so I don't want to move them. A dependency Upload -> Config is fine IMO but Config -> Upload is weird IMO.

**Comment by karottenreibe** [comment]
rfr again :)
