### PR TITLE
Stacktrace

### LINKED ISSUE #55: Write stack traces in case of profiler crashes
We recently had the profiler crash mysteriously. This is very hard to debug. We need a way to get a proper stack trace in case our code crashes e.g. with an access violation.

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #55

- [ ] Tests written
- [x] Documentation updated

Since this error handling is inherently untestable, I instead tested this manually by introducing a simple segfault into the profiler. I tested both with and without the IGNORE_EXCEPTIONS variable.

I verified that the resulting stack traces are readable and contain the function names. This, however, requires that the .pdb files are present next to the .dll files

### CODE REVIEW

File: Profiler/CProfilerCallback.h [hunk 1]
```diff
@@ -160,4 +159,13 @@ class CProfilerCallback : public CProfilerCallbackBase {
...
 	int writeFileVersionInfo(LPCWSTR moduleFileName, char* buffer, size_t bufferSize);
+
+	HRESULT JITCompilationFinishedImplementation(FunctionID functionID, HRESULT hrStatus, BOOL fIsSafeToBlock);
+	HRESULT ShutdownImplementation();
+	HRESULT AssemblyLoadFinishedImplementation(AssemblyID assemblyID, HRESULT hrStatus);
+	HRESULT JITInliningImplementation(FunctionID callerID, FunctionID calleeID, BOOL *pfShouldInline);
+	HRESULT InitializeImplementation(IUnknown *pICorProfilerInfoUnk);
+
+	/** Logs a stack trace. If true is returned, the calling code should continue, otherwise it should rethrow the exception. */
+	bool handleException(std::string context);
```
Comment (zipperle) [inline Profiler/CProfilerCallback.h]: Why not rethrow the exception in this function?

Comment (karottenreibe) [reply Profiler/CProfilerCallback.h]: unfortunately, that's not possible. I have to catch (...) in the outer function so I can catch Windows structured exceptions as well (e.g. division by 0, general protection fault, ...) since these are not represented by actual exception objects. Thus, I can only rethrow via a throw; statement. And this only works in the context of a catch statement, which I don't have here anymore :-(

**Comment by karottenreibe** [comment]
rfr again @zipperle

**Comment by karottenreibe** [comment]
@zipperle I fixed the rethrow as we discussed :-) 
rfr again

File: Profiler/CProfilerCallback.cpp [hunk 2]
```diff
@@ -282,6 +326,24 @@ void CProfilerCallback::getAssemblyInfo(AssemblyID assemblyId, WCHAR *assemblyNa
...
+	}
+	catch (...) {
+		handleException("JITCompilationFinished");
+		return S_OK;
+	}
+}
+
+void CProfilerCallback::handleException(std::string context) {
+	Debug::logStacktrace(context);
+	if (getOption("IGNORE_EXCEPTIONS") != "1") {
```
Comment (zipperle) [inline Profiler/CProfilerCallback.cpp]: Can you add this parameter to the documentation?

**Comment by karottenreibe** [comment]
rfr
